name: build

on: [push]

jobs:
  A:
    runs-on: ubuntu-latest
    environment: ${{ ('prod') || ('dev') }}
    steps:
      - name: Check identity
        run: |
          echo "A prod = ${{ env.A }}"
          echo "B dev = ${{ env.B }}"
