name: build

on: [push]

jobs:
  B:
    runs-on: ubuntu-latest
    outputs:
      cond: False
    steps:
      - name: fail
        run:  echo "run"
  A:
    needs: [B]
    runs-on: ubuntu-latest
    if: needs.B.outputs.cond == 'False'
    environment: dev
    steps:
      - name: Check identity
        run: echo "B dev = ${{ vars.B }}"
