name: build

on: [push]

jobs:
  A:
    runs-on: ubuntu-latest
    outputs:
      check_value: ${{ steps.check.outputs.check_value }}
    environment: correct_env
    steps:
      - name: check
        id: check
        run: |
          check_value='False'
          if [ ${{ vars.CHECK == 'True' }} ]; then
            check_value='True'

  B:
    needs: [A]
    runs-on: ubuntu-latest
    if: needs.A.outputs.check_value == 'True'
    steps:
      - name: Check identity
        run: echo "correct environment passed"
