name: build

on: [push]

jobs:
  B:
    runs-on: ubuntu-latest
    outputs:
      cond: True
    steps:
      - name: fail
        run:  echo "run"
  A:
    needs: [B]
    runs-on: ubuntu-latest
    environment: ${{ (needs.B.outputs.cond == 'False') && ('prod') || ('dev') }}
    steps:
      - name: Check identity
        run: |
          echo "A prod = ${{ vars.A }}"
          echo "B dev = ${{ vars.B }}"
