name: build

on: [push]

jobs:
  authorize-internal:
    runs-on: ubuntu-latest
    outputs:
      internal_run: True
    steps:
      - name: Authorize internal
        run: echo "authorized"
  
  authorize-external:
    runs-on: ubuntu-latest
    outputs:
      check_value: ${{ steps.check.outputs.check_value }}
    environment: correct_env
    steps:
      - name: check
        id: check
        run: |
          check_value='False'
          if [ ${{ vars.CHECK == 'True' }} ]; then
            check_value='True'
          fi
          echo "check_value=$check_value" >> "$GITHUB_OUTPUT"

  authorize:
    needs: [authorize-external, authorize-internal]
    runs-on: ubuntu-latest
    if: |
      always() &&
      !failure() && !cancelled() &&
      (needs.authorize-internal.result == 'success' || needs.authorize-external.result == 'success') &&
      (needs.authorize-internal.result != needs.authorize-external.result) &&
      (needs.authorize-external.outputs.check_value == 'True' || needs.authorize-internal.outputs.internal_run == 'True')
    steps:
      - name: Check identity
        run: echo "correct environment passed"
